####################################################
# Pmacct - nfacctd daemon
#
# This docker-compose file spins up a nfacctd container, and can be used as target for traffic from the reproducer.
# The nfacctd daemon can be used as an ipfix-only collector, or as an ipfix+bgp or ipfix+bmp collector.
# The configuration included here is very basic, printing aggregated flow data to files. 
# The daemon binds to 0.0.0.0 on the host system.
#
# Refer to https://github.com/pmacct/pmacct for additional information. 
#
####################################################
version: '3'
services:
  nfacctd:
    image: pmacct/nfacctd:bleeding-edge
    container_name: nfacctd-example
    volumes:
      - ./__tmp_pmacct-output:/var/log/pmacct
      #
      #   nfacctd config files (to be mapped to /etc/pmacct/nfacctd.conf in the container)
      #     --> enable only one of the following depending on the reproduced traffic
      #
      #- ./nfacctd-example-ipfix.conf:/etc/pmacct/nfacctd.conf
      - ./nfacctd-example-ipfix+bgp.conf:/etc/pmacct/nfacctd.conf
      #- ./nfacctd-example-ipfix+bmp.conf:/etc/pmacct/nfacctd.conf
      #
    network_mode: host
    privileged: true
    restart: unless-stopped
