name: Basic Checks

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Set up loopback interfaces
        run: |
          sudo ifconfig lo:1 192.168.100.1 up
          sudo ifconfig lo:2 192.168.100.2 up

      - name: Start Listener
        run: |
          nc -l -6 -p 9991 & echo $! > listener_pid.txt

      - name: Start TCPDump in background
        run: |
          sudo tcpdump -i lo -c 6 &
          echo "$!" >> tcpdump_pid.txt
          
      - name: Debug IP Configuration
        run: |
          ip a
          
      - name: Run main.py
        run: |
          python main.py -v -t examples/ipfix-traffic.yml

      - name: Stop Listener
        run: |
          pid=$(cat listener_pid.txt)
          sudo kill -SIGINT $pid

      - name: Stop TCPDump
        run: |
          pid=$(cat tcpdump_pid.txt)
          sudo kill -SIGINT $pid
